"""Optional AI advisory check via Snowflake Cortex.

A semantic second opinion on the build, OFF by default. It is deliberately
boxed in so it cannot undermine the deterministic engine:

- It never sets a verdict. It returns WARN (a note) or PASS, never FAIL or
  BLOCKER, so the deterministic D-*/S-* checks alone decide pass/fail. Per the
  verdict model a WARN can only hold a run at READY_WITH_NOTES, never REVIEW or
  BLOCKED.
- It never generates a QC query. The deterministic checks build their own
  queries from sqlglot templates; this check only *reads* the build and asks the
  model to comment.
- It is read-only and in-database: SNOWFLAKE.CORTEX.COMPLETE is a single SELECT
  on the same guarded session, so no data leaves Snowflake and no API key exists.
- It is off until PLUMB_CORTEX_MODEL is set and the check is enabled; otherwise
  it SKIPs cleanly.

The point is to surface semantic issues a linter cannot see (wrong grain, a
suspicious date window, a metric averaged instead of summed) for a human to
confirm - advisory only.
"""

from __future__ import annotations

from plumb.ai.client import cortex_enabled, get_client
from plumb.checks._base import build_result
from plumb.engine.models import CheckFamily, ExecutionType, Severity, Status
from plumb.engine.registry import CheckContext, register_check

_SYSTEM = (
    "You are a senior analytics engineer reviewing a Snowflake SQL build before "
    "it ships to a BI team. Deterministic linters already cover cross joins, NULL "
    "traps, grain uniqueness, null rates, and freshness, so do NOT repeat those. "
    "Comment ONLY on semantic or business-logic issues a linter cannot see, such "
    "as: an aggregation at the wrong grain, a date filter or window that looks "
    "wrong, a CASE that misses cases, a metric computed incorrectly (for example "
    "averaging a ratio that should be summed then divided), a join or filter that "
    "silently drops rows, or suspicious hardcoded business logic. Be concrete and "
    "conservative: flag only a real, likely problem, not style. Reply with a short "
    "list, one concern per line starting with '- '. If nothing stands out, reply "
    "with exactly: OK"
)

_MAX_SQL_CHARS = 6000  # keep the prompt bounded; the model sees the build, not data
_MAX_TOKENS = 400


@register_check(
    check_id="A-SEM-001",
    name="AI advisory: semantic review of the build (Cortex)",
    # An execution check (it needs the live session for Cortex). Grouped under
    # assertions since there is no dedicated AI family yet; the A- id and name
    # keep it clearly distinct and it can only ever WARN.
    family=CheckFamily.ASSERTIONS,
    default_severity=Severity.LOW,
    execution_type=ExecutionType.EXECUTION,
)
def a_sem_001(ctx: CheckContext, params: dict):
    if not ctx.sql_text:
        return build_result(ctx, "A-SEM-001", Status.SKIP, observed="no SQL provided")
    if not cortex_enabled():
        return build_result(
            ctx,
            "A-SEM-001",
            Status.SKIP,
            observed="AI assist is off; set PLUMB_CORTEX_MODEL to enable",
        )
    client = get_client(session=ctx.session)
    if client is None:
        return build_result(
            ctx,
            "A-SEM-001",
            Status.SKIP,
            observed="AI assist needs a live Snowflake session (run live, not static-only)",
        )
    sql = ctx.sql_text.strip()[:_MAX_SQL_CHARS]
    try:
        reply = client.complete(_SYSTEM, f"Build under review:\n\n{sql}", _MAX_TOKENS)
    except Exception as exc:  # noqa: BLE001 - an advisory check must never break a run
        return build_result(
            ctx, "A-SEM-001", Status.SKIP, observed=f"AI assist unavailable: {exc}"
        )
    concerns = _parse_concerns(reply)
    if not concerns:
        return build_result(
            ctx, "A-SEM-001", Status.PASS, observed="AI review raised no semantic concerns"
        )
    return build_result(
        ctx,
        "A-SEM-001",
        Status.WARN,
        observed=f"AI review (advisory): {len(concerns)} point(s) to confirm - {concerns[0]}",
        expected="an analyst confirms each point; advisory only, never sets the verdict",
        evidence_rows=[{"concern": c} for c in concerns],
        remediation=(
            "Generated by Snowflake Cortex as a second opinion. Treat as a prompt to "
            "double-check, not a finding: verify against the data before acting."
        ),
    )


def _parse_concerns(reply: str) -> list[str]:
    """Pull the model's bullet points; an 'OK' (or empty) reply means no concern."""
    text = (reply or "").strip()
    if not text or text.upper().rstrip(".!") == "OK":
        return []
    out: list[str] = []
    for raw in text.splitlines():
        line = raw.strip().lstrip("-*•").strip()
        if line and line.upper() != "OK":
            out.append(line[:200])
    return out[:10]
